/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Customer struct {

	Id int64 `json:"id"`

	Firstname string `json:"firstname,omitempty"`

	Lastname string `json:"lastname,omitempty"`

	Active bool `json:"active,omitempty"`

	Birhday string `json:"birhday,omitempty"`

	Vat int64 `json:"vat,omitempty"`

	Email string `json:"email,omitempty"`

	Phone string `json:"phone,omitempty"`

	Company string `json:"company,omitempty"`

	Gender string `json:"gender,omitempty"`

	ReceivedNewsletter bool `json:"received_newsletter,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
