/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type I18nProductSeo struct {

	Title string `json:"title,omitempty"`

	Keywords string `json:"keywords,omitempty"`

	Description string `json:"description,omitempty"`
}
