/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type I18nProduct struct {

	Locale string `json:"locale"`

	Name string `json:"name"`

	Synopsis string `json:"synopsis,omitempty"`

	Description string `json:"description,omitempty"`

	Characteristics string `json:"characteristics,omitempty"`

	Seo *I18nProductSeo `json:"seo,omitempty"`
}
