/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type I18n struct {

	Locale string `json:"locale"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`
}
