/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2004 struct {

	Data []Payment `json:"data,omitempty"`

	Meta *InlineResponse2001Meta `json:"meta,omitempty"`
}
