/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MetaPartialResponse struct {

	FirstPageUrl string `json:"first_page_url,omitempty"`

	LastPageUrl string `json:"last_page_url,omitempty"`

	NextPageUrl string `json:"next_page_url,omitempty"`

	Path string `json:"path,omitempty"`

	PrevPageUrl string `json:"prev_page_url,omitempty"`
}
