/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Options struct {

	Id int64 `json:"id,omitempty"`

	Position int64 `json:"position,omitempty"`

	AuxCode string `json:"aux_code,omitempty"`

	I18n *I18n `json:"i18n,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
