/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Product struct {

	Id int64 `json:"id"`

	Sku string `json:"sku,omitempty"`

	Manual string `json:"manual,omitempty"`

	UrlVideo string `json:"url_video,omitempty"`

	// channels that resource are showed
	Visibility []string `json:"visibility,omitempty"`

	InHomepage bool `json:"in_homepage,omitempty"`

	IsPrefered bool `json:"is_prefered,omitempty"`

	IsDigital bool `json:"is_digital,omitempty"`

	UrlDigital string `json:"url_digital,omitempty"`

	IsNew bool `json:"is_new,omitempty"`

	I18n *I18nProduct `json:"i18n,omitempty"`

	Active bool `json:"active,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	ExpiresAt time.Time `json:"expires_at,omitempty"`
}
